INSERT INTO `membre`(`id_membre`, `pseudo`, `mdp`, `nom`, `prenom`, `telephone`, `email`, `civilite`, `statut`, `date_enregistrement`) VALUES
('NULL', 'WolfFrench          ', 'Aaaaaaa0', 'Laborde','Jean-pierre' ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'NightGt             ', 'Aaaaaaa0', 'Gallet' ,'Clement'     ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'BraveLotus          ', 'Aaaaaaa0', 'Winter' ,'Thomas'      ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'CookieChocolatine   ', 'Aaaaaaa0',   'Dubar','Chloe'       ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'GhostPepito         ', 'Aaaaaaa0', 'Fellier','Elodie'      ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'DinoLegend          ', 'Aaaaaaa0', 'Grand'  ,'Fabrice'     ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'BlackFrench         ', 'Aaaaaaa0', 'Collier','Melanie'     ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'OscarDocteur        ', 'Aaaaaaa0', 'Blanchet,'Laura'       ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'PortePoney          ', 'Aaaaaaa0', 'Miller' ,'Guillaume'   ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'JustToto            ', 'Aaaaaaa0', 'Perrin' ,'Celine'      ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'ViperTruck          ', 'Aaaaaaa0', 'Cottet' ,'Julien'      ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'SteelWhite          ', 'Aaaaaaa0', 'Vignal' ,'Mathieu'     ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'HyperRussian        ', 'Aaaaaaa0', 'Desprez','Thierry'     ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'OxygèneX            ', 'Aaaaaaa0', 'Thoyer' ,'Amandine'    ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'FlyingStorm         ', 'Aaaaaaa0', 'Durand' ,'Damien'      ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'PorteWait           ', 'Aaaaaaa0', 'Chevel' ,'Daniel'      ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'FishSunshine        ', 'Aaaaaaa0', 'Martin' ,'Nathalie'    ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'DogFlying           ', 'Aaaaaaa0', 'Lagarde','Benoit'      ,'0101010101','email@mail.fr' , 'm', '0', NOW()),
('NULL', 'FreestyleCaptain    ', 'Aaaaaaa0', 'Sennard','Emilie'      ,'0101010101','email@mail.fr' , 'f', '0', NOW()),
('NULL', 'TruckDrake          ', 'Aaaaaaa0', 'Lafaye' ,'Stephanie'   ,'0101010101','email@mail.fr' , 'f', '0', NOW());
